services:
  postgres:
    image: postgres:15
    container_name: postgres-hibernate
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: it_department
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hibernate-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-hibernate
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - hibernate-net

networks:
  hibernate-net: